<?xml version="1.0" encoding="utf-8"?>
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net7.0</TargetFramework>
    <OutputType>Library</OutputType>
    <PackageId>Alma.DynamoDB</PackageId>
    <Version>4.2.0</Version>
    <RepositoryUrl>https://github.com/almacareer/prc-fdynamodb</RepositoryUrl>
  </PropertyGroup>

  <ItemGroup>
    <Compile Include="AssemblyInfo.fs" />
  </ItemGroup>

  <ItemGroup>
    <Compile Include="src/DynamoDB.fs" />
  </ItemGroup>

  <Import Project=".paket\Paket.Restore.targets" />
</Project>
